In [1]:
import numpy as np

In [2]:
x = np.array([[0,1],[1,0]])
y = np.array([[0,-1j],[1j,0]])
z = np.array([[1,0],[0,-1]])
c = np.array([[0,0],[1,0]])
a = np.array([[0,1],[0,0]])
I = np.array([[1,0],[0,1]])
i = np.complex(0,1)
h = np.array([[1,1],[1,-1]])*(1/np.sqrt(2))

In [3]:
cnot = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

In [4]:
def rev_prod(a,b):
    return b@a

def prod(a,b):
    return a@b

In [18]:
m = (I-z)/2
p = (I+z)/2
print(m)
print(p)

[[0. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 0.]]


In [16]:
c

array([[0, 0],
       [1, 0]])

In [17]:
a

array([[0, 1],
       [0, 0]])

# Pauli gate product

In [8]:
assert np.all(np.equal(prod(x,y),i*z))
assert np.all(np.equal(prod(x,z),-i*y))

assert np.all(np.equal(prod(y,x),-i*z))
assert np.all(np.equal(prod(y,z),i*x))

assert np.all(np.equal(prod(z,x),i*y))
assert np.all(np.equal(prod(z,y),-i*x))

In [9]:
assert np.all(np.equal(rev_prod(x,y),-i*z))
assert np.all(np.equal(rev_prod(x,z),i*y))

assert np.all(np.equal(rev_prod(y,x),i*z))
assert np.all(np.equal(rev_prod(y,z),-i*x))

assert np.all(np.equal(rev_prod(z,x),-i*y))
assert np.all(np.equal(rev_prod(z,y),i*x))

# Ladder pauli products

In [10]:
ket_0 = np.array([[1],[0]])
ket_1 = np.array([[0],[1]])

assert np.all(np.equal(c@ket_0,ket_1))
assert np.all(np.equal(a@ket_1,ket_0))

assert np.all(np.equal(a@a,0))
assert np.all(np.equal(c@c,0))

assert np.all(np.equal(prod(a,c),(I+z)/2))
assert np.all(np.equal(prod(c,a),(I-z)/2))
              
assert np.all(np.equal(rev_prod(a,c),(I-z)/2))
assert np.all(np.equal(rev_prod(c,a),(I+z)/2))

In [11]:
assert np.all(np.equal(prod(c,x),(I-z)/2))
assert np.all(np.equal(prod(c,y),(-i*I +i*z)/2))
assert np.all(np.equal(prod(c,z),c))
assert np.all(np.equal(prod(x,c),(I+z)/2))
assert np.all(np.equal(prod(y,c),(-i*I-i*z)/2))
assert np.all(np.equal(prod(z,c),-c))
              
assert np.all(np.equal(prod(a,x),(I+z)/2))
assert np.all(np.equal(prod(a,y),(i*I+i*z)/2))
assert np.all(np.equal(prod(a,z),-a))
assert np.all(np.equal(prod(x,a),(I-z)/2))
assert np.all(np.equal(prod(y,a),(i*I-i*z)/2))
assert np.all(np.equal(prod(z,a),a))

In [12]:
assert np.all(np.equal(rev_prod(x,c),(I-z)/2))
assert np.all(np.equal(rev_prod(x,a),(I+z)/2))

assert np.all(np.equal(rev_prod(y,c),(-i*I+i*z)/2))
assert np.all(np.equal(rev_prod(y,a),(i*I+i*z)/2))

assert np.all(np.equal(rev_prod(z,c),c))
assert np.all(np.equal(rev_prod(z,a),-a))

assert np.all(np.equal(rev_prod(c,x),(I+z)/2))
assert np.all(np.equal(rev_prod(c,y),(-i*I-i*z)/2))
assert np.all(np.equal(rev_prod(c,z),-c))

assert np.all(np.equal(rev_prod(a,x),(I-z)/2))
assert np.all(np.equal(rev_prod(a,y),(i*I-i*z)/2))
assert np.all(np.equal(rev_prod(a,z),a))

# Circuit identities

### Single qubit identities

$X_1H_2 \leftrightarrow Z_1H_2 $

$H_1X_2 \leftrightarrow H_1Z_2 $

### CNOT identities
$Z_1\text{CNOT}_{1,2} \leftrightarrow \text{CNOT}_{1,2}Z_1$

In [13]:
assert np.all(np.equal(x@h,h@z))
assert np.all(np.equal(h@x,z@h))


In [14]:
print(np.kron(x,I))
print(cnot)
print(np.kron(x,I)@cnot)
print(cnot@np.kron(x,I))

[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[0 0 0 1]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]]
[[0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]]


In [15]:
print(c)
print(x-np.complex(0,1)*y)

[[0 0]
 [1 0]]
[[0.+0.j 0.+0.j]
 [2.+0.j 0.+0.j]]


In [44]:
import qiskit as qk

In [77]:
qb = qk.QuantumRegister(1)
cb = qk.ClassicalRegister(1)
qc = qk.QuantumCircuit(qb,cb)

qc.h(qb[0])
qc.x(qb[0])
qc.h(qb[0])

qc.h(qb[0])
qc.rx(np.pi/2,qb[0])
qc.y(qb[0])
qc.rx(-np.pi/2,qb[0])
qc.h(qb[0])


qc.measure(qb,cb)
job = qk.execute(qc,backend=qk.Aer.get_backend('qasm_simulator'),shots=1000)
result = job.result().get_counts(qc)
print(result)


{'1': 1000}
